export default {
  NOTES: "NOTES",
  NEXT_NOTES: "NEXT_NOTES",
  CURRENT_PAGE: "CURRENT_PAGE",
  TOGGLE_LOADER: "TOGGLE_LOADER",
  SHOW_DIALOG: "SHOW_DIALOG",
  SHOW_PARENT_DIALOG: "SHOW_PARENT_DIALOG",
  SHOW_CHILD_DIALOG: "SHOW_CHILD_DIALOG",
  SHOW_CHILD_DIALOG_EDIT_TEXT: "SHOW_CHILD_DIALOG_EDIT_TEXT",
  IS_LOGIN: "IS_LOGIN",
  DRAWER: "DRAWER",
  SHOW_NOTIFICATION: "SHOW_NOTIFICATION",
  CURRENT_NOTE: "CURRENT_NOTE",
  CATS: "CATS",
  MAPS: "MAPS"
};
