export default {
  NOTES: "NOTES",
  NEXT_NOTES: "NEXT_NOTES",
  CURRENT_PAGE: "CURRENT_PAGE",
  TOGGLE_LOADER: "TOGGLE_LOADER",
  SHOW_DIALOG: "SHOW_DIALOG",
  IS_LOGIN: "IS_LOGIN",
  DRAWER: "DRAWER",
  SHOW_NOTIFICATION: "SHOW_NOTIFICATION",
  CURRENT_NOTE: "CURRENT_NOTE"
};
